import { useState } from 'react';
import { Link, router, useForm } from '@inertiajs/react';
import { BookOpen, CalendarClock, FileEdit, Plus, Search, Tags, Trash2 } from 'lucide-react';
import AdminLayout from '@/Layouts/AdminLayout';

function Stat({ label, value, icon: Icon, color }) { return <div className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-wider text-neutral-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div><Icon className={`h-7 w-7 ${color}`} /></div></div>; }

export default function BlogIndex({ posts, categories, tags, filters, stats }) {
    const [selected, setSelected] = useState([]);
    const [taxonomy, setTaxonomy] = useState('category');
    const categoryForm = useForm({ name: '', slug: '', description: '', meta_title: '', meta_description: '', is_active: true });
    const tagForm = useForm({ name: '', slug: '' });
    const filter = (name, value) => router.get(route('admin.blog.index'), { ...filters, [name]: value || undefined }, { preserveState: true, replace: true });
    const bulk = (action) => { if (selected.length && (action !== 'delete' || confirm('Move selected posts to trash?'))) router.post(route('admin.blog.bulk'), { ids: selected, action }, { onSuccess: () => setSelected([]) }); };
    return <AdminLayout title="Blog management"><div className="mx-auto max-w-7xl space-y-6">
        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-bold">Blog</h1><p className="mt-1 text-sm text-neutral-500">Create, schedule, optimize and manage your SEO content.</p></div><Link href={route('admin.blog.create')} className="inline-flex items-center justify-center gap-2 rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> New article</Link></div>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="All posts" value={stats.total} icon={BookOpen} color="text-blue-500" /><Stat label="Published" value={stats.published} icon={BookOpen} color="text-emerald-500" /><Stat label="Drafts" value={stats.draft} icon={FileEdit} color="text-amber-500" /><Stat label="Scheduled" value={stats.scheduled} icon={CalendarClock} color="text-violet-500" /></div>
        <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
            <section className="overflow-hidden rounded-xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900">
                <div className="flex flex-wrap gap-3 border-b border-neutral-200 p-4 dark:border-neutral-800"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-neutral-400" /><input defaultValue={filters.search || ''} onKeyDown={(e) => e.key === 'Enter' && filter('search', e.currentTarget.value)} placeholder="Search title or slug…" className="w-full rounded-lg border-neutral-300 py-2 pl-9 text-sm dark:border-neutral-700 dark:bg-neutral-800" /></div><select value={filters.status || ''} onChange={(e) => filter('status', e.target.value)} className="rounded-lg border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-800"><option value="">All statuses</option><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option></select><select value={filters.category || ''} onChange={(e) => filter('category', e.target.value)} className="rounded-lg border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-800"><option value="">All categories</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
                {selected.length > 0 && <div className="flex items-center gap-2 bg-brand-50 px-4 py-2 text-sm dark:bg-brand-950"><span className="mr-auto font-medium">{selected.length} selected</span><button onClick={() => bulk('publish')} className="rounded px-2 py-1 font-medium">Publish</button><button onClick={() => bulk('draft')} className="rounded px-2 py-1 font-medium">Draft</button><button onClick={() => bulk('delete')} className="rounded px-2 py-1 font-medium text-red-600">Delete</button></div>}
                <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-neutral-50 text-left text-xs uppercase tracking-wide text-neutral-500 dark:bg-neutral-800"><tr><th className="px-4 py-3"><input type="checkbox" checked={posts.data.length > 0 && selected.length === posts.data.length} onChange={(e) => setSelected(e.target.checked ? posts.data.map((p) => p.id) : [])} /></th><th className="px-4 py-3">Article</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Updated</th><th /></tr></thead><tbody className="divide-y divide-neutral-100 dark:divide-neutral-800">{posts.data.map((post) => <tr key={post.id}><td className="px-4 py-4"><input type="checkbox" checked={selected.includes(post.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, post.id] : selected.filter((id) => id !== post.id))} /></td><td className="px-4 py-4"><Link href={route('admin.blog.edit', post.id)} className="font-semibold hover:text-brand-600">{post.title}</Link><div className="mt-1 text-xs text-neutral-400">/blog/{post.slug} {post.category ? `· ${post.category.name}` : ''}</div></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${post.status === 'published' ? 'bg-emerald-50 text-emerald-700' : post.status === 'scheduled' ? 'bg-violet-50 text-violet-700' : 'bg-amber-50 text-amber-700'}`}>{post.status}</span></td><td className="px-4 py-4 text-neutral-500">{new Date(post.updated_at).toLocaleDateString()}</td><td className="px-4 py-4 text-right"><Link href={route('admin.blog.edit', post.id)} className="mr-2 inline-flex rounded-lg p-2 text-neutral-400 hover:bg-neutral-100 hover:text-brand-600"><FileEdit className="h-4 w-4" /></Link><button onClick={() => confirm('Move this article to trash?') && router.delete(route('admin.blog.destroy', post.id))} className="rounded-lg p-2 text-neutral-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></td></tr>)}{!posts.data.length && <tr><td colSpan="5" className="px-6 py-16 text-center text-neutral-400">No blog posts match these filters.</td></tr>}</tbody></table></div>
                {posts.links?.length > 3 && <div className="flex flex-wrap gap-2 border-t border-neutral-200 p-4 dark:border-neutral-800">{posts.links.map((link, i) => link.url ? <Link key={i} href={link.url} className={`rounded border px-3 py-1.5 text-sm ${link.active ? 'border-brand-500 bg-brand-500 text-white' : 'border-neutral-200 dark:border-neutral-700'}`} dangerouslySetInnerHTML={{ __html: link.label }} /> : null)}</div>}
            </section>
            <aside className="h-fit rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center gap-2"><Tags className="h-5 w-5 text-brand-500" /><h2 className="font-bold">Taxonomy</h2></div><div className="mt-4 flex rounded-lg bg-neutral-100 p-1 dark:bg-neutral-800"><button onClick={() => setTaxonomy('category')} className={`flex-1 rounded-md px-3 py-1.5 text-sm ${taxonomy === 'category' ? 'bg-white shadow dark:bg-neutral-700' : ''}`}>Categories</button><button onClick={() => setTaxonomy('tag')} className={`flex-1 rounded-md px-3 py-1.5 text-sm ${taxonomy === 'tag' ? 'bg-white shadow dark:bg-neutral-700' : ''}`}>Tags</button></div>
                {taxonomy === 'category' ? <><form onSubmit={(e) => { e.preventDefault(); categoryForm.post(route('admin.blog.categories.store'), { preserveScroll: true, onSuccess: () => categoryForm.reset() }); }} className="mt-4 space-y-2"><input value={categoryForm.data.name} onChange={(e) => categoryForm.setData('name', e.target.value)} required placeholder="Category name" className="w-full rounded-lg border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-800" /><input value={categoryForm.data.slug} onChange={(e) => categoryForm.setData('slug', e.target.value)} placeholder="slug (automatic)" className="w-full rounded-lg border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-800" /><button className="w-full rounded-lg bg-neutral-900 px-3 py-2 text-sm font-semibold text-white dark:bg-white dark:text-neutral-900">Add category</button></form><div className="mt-4 space-y-2">{categories.map((c) => <div key={c.id} className="flex items-center rounded-lg bg-neutral-50 px-3 py-2 text-sm dark:bg-neutral-800"><span className="min-w-0 flex-1 truncate">{c.name} <span className="text-neutral-400">({c.posts_count})</span></span><button onClick={() => c.posts_count === 0 && confirm('Delete category?') && router.delete(route('admin.blog.categories.destroy', c.id), { preserveScroll: true })} disabled={c.posts_count > 0} title={c.posts_count > 0 ? 'Remove or reassign posts first' : 'Delete'} className="text-neutral-400 disabled:opacity-20"><Trash2 className="h-4 w-4" /></button></div>)}</div></> : <><form onSubmit={(e) => { e.preventDefault(); tagForm.post(route('admin.blog.tags.store'), { preserveScroll: true, onSuccess: () => tagForm.reset() }); }} className="mt-4 flex gap-2"><input value={tagForm.data.name} onChange={(e) => tagForm.setData('name', e.target.value)} required placeholder="New tag" className="min-w-0 flex-1 rounded-lg border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-800" /><button className="rounded-lg bg-neutral-900 px-3 text-sm font-semibold text-white dark:bg-white dark:text-neutral-900">Add</button></form><div className="mt-4 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag.id} className="inline-flex items-center gap-1 rounded-full bg-neutral-100 px-3 py-1 text-xs dark:bg-neutral-800">#{tag.name}<button onClick={() => tag.posts_count === 0 && router.delete(route('admin.blog.tags.destroy', tag.id), { preserveScroll: true })} disabled={tag.posts_count > 0} className="text-neutral-400 disabled:hidden">×</button></span>)}</div></>}
            </aside>
        </div>
    </div></AdminLayout>;
}
