import { Head, Link, router, useForm } from '@inertiajs/react';
import ClientLayout from '@/Layouts/ClientLayout';
import { AlertTriangle, CheckCircle2, ChevronRight, Mail, Plus, RefreshCw, Server, ShieldCheck, Trash2, X } from 'lucide-react';
import { useState } from 'react';

const providers = {
    gmail: { name: 'Gmail / Google Workspace', short: 'G', color: 'bg-red-50 text-red-600', description: 'Connect securely with Google OAuth—no mailbox password required.' },
    microsoft_365: { name: 'Microsoft 365 / Outlook', short: 'M', color: 'bg-blue-50 text-blue-600', description: 'Connect through Microsoft OAuth.' },
    imap_smtp: { name: 'Other email (IMAP / SMTP)', short: '@', color: 'bg-violet-50 text-violet-600', description: 'For cPanel, Zoho, Fastmail and private mail servers.' },
};

function AccountCard({ account }) {
    const provider = providers[account.provider] || providers.imap_smtp;
    return <div className="flex items-center gap-3 rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-700 dark:bg-neutral-900"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl font-bold ${provider.color}`}>{provider.short}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-semibold text-neutral-900 dark:text-white">{account.display_name}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${account.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{account.status}</span></div><p className="truncate text-xs text-neutral-500">{account.email} · {provider.name}</p>{account.last_synced_at && <p className="mt-1 text-[11px] text-neutral-400">Synced {new Date(account.last_synced_at).toLocaleString()}</p>}{account.last_sync_error && <p className="mt-1 line-clamp-2 text-[11px] text-red-600">{account.last_sync_error}</p>}</div><button onClick={() => router.post(route('client.inbox.email.sync', account.id))} className="rounded-lg p-2 text-neutral-400 hover:bg-neutral-100 hover:text-brand-600" title="Sync now"><RefreshCw className="h-4 w-4" /></button><button onClick={() => confirm('Disconnect this mailbox? Existing conversations will be kept.') && router.delete(route('client.inbox.email.destroy', account.id))} className="rounded-lg p-2 text-neutral-400 hover:bg-red-50 hover:text-red-600" title="Disconnect"><Trash2 className="h-4 w-4" /></button></div>;
}

function MailboxForm({ type, imapExtensionAvailable, onClose }) {
    const form = useForm({ provider: type, email: '', display_name: '', imap_host: '', imap_port: 993, imap_encryption: 'ssl', smtp_host: '', smtp_port: 587, smtp_encryption: 'tls', username: '', password: '', verify_tls: true });
    const setEmail = value => { form.setData(data => ({ ...data, email: value, username: data.username || value })); };
    const submit = event => { event.preventDefault(); form.post(route('client.inbox.email.generic.store'), { preserveScroll: true, onSuccess: onClose }); };
    return <form onSubmit={submit} className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-neutral-900 dark:text-white">{providers[type].name}</h3><p className="text-xs text-neutral-500">Add as many separate mailboxes as your team uses.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-neutral-400 hover:bg-neutral-100"><X className="h-4 w-4" /></button></div>{!imapExtensionAvailable && <div className="flex gap-2 rounded-lg bg-amber-50 p-3 text-xs text-amber-700"><AlertTriangle className="h-4 w-4 shrink-0" />PHP IMAP is not installed on this server. This only affects manual IMAP accounts; Google and Microsoft OAuth do not need it.</div>}<div className="grid gap-3 sm:grid-cols-2"><Input label="Mailbox email" value={form.data.email} onChange={setEmail} type="email" /><Input label="Display name" value={form.data.display_name} onChange={value => form.setData('display_name', value)} optional /></div><div className="grid grid-cols-[1fr_90px] gap-3"><Input label="Incoming IMAP server" value={form.data.imap_host} onChange={value => form.setData('imap_host', value)} /><Input label="Port" value={form.data.imap_port} onChange={value => form.setData('imap_port', Number(value))} type="number" /></div><Select label="IMAP security" value={form.data.imap_encryption} onChange={value => form.setData('imap_encryption', value)} /><div className="grid grid-cols-[1fr_90px] gap-3"><Input label="Outgoing SMTP server" value={form.data.smtp_host} onChange={value => form.setData('smtp_host', value)} /><Input label="Port" value={form.data.smtp_port} onChange={value => form.setData('smtp_port', Number(value))} type="number" /></div><Select label="SMTP security" value={form.data.smtp_encryption} onChange={value => form.setData('smtp_encryption', value)} /><div className="grid gap-3 sm:grid-cols-2"><Input label="Username" value={form.data.username} onChange={value => form.setData('username', value)} /><Input label="Password / app password" value={form.data.password} onChange={value => form.setData('password', value)} type="password" /></div>{Object.keys(form.errors).length > 0 && <p className="rounded-lg bg-red-50 px-3 py-2 text-xs text-red-600">{Object.values(form.errors)[0]}</p>}<button disabled={form.processing || !imapExtensionAvailable} className="w-full rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{form.processing ? 'Testing connection…' : 'Test and add mailbox'}</button></form>;
}

export default function EmailSetup({ accounts = [], googleEnabled, googleCallbackUrl, microsoftEnabled, microsoftCallbackUrl, imapExtensionAvailable }) {
    const [adding, setAdding] = useState(null);
    const activeCount = accounts.filter(account => account.status === 'active').length;
    return <ClientLayout><Head title="Email accounts" /><div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
        <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-brand-600"><Mail className="h-4 w-4" />EMAIL MASTEBOX</div><h1 className="text-2xl font-bold text-neutral-900 dark:text-white">Connected email accounts</h1><p className="mt-1 max-w-2xl text-sm text-neutral-500">Bring every Gmail, Microsoft 365 and IMAP mailbox into one focused email workspace. Each mailbox keeps its own identity for receiving and sending.</p></div><Link href={route('client.inbox.email-inbox')} className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Open Email MasteBox<ChevronRight className="h-4 w-4" /></Link></header>
        <div className="grid gap-3 sm:grid-cols-3"><Stat value={accounts.length} label="Accounts added" /><Stat value={activeCount} label="Ready to send & receive" good /><Stat value={accounts.filter(account => account.last_sync_error).length} label="Needs attention" warning /></div>
        <section className="rounded-2xl border border-neutral-200 bg-neutral-50/60 p-4 dark:border-neutral-800 dark:bg-neutral-900/50"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-neutral-900 dark:text-white">Your mailboxes</h2><p className="text-xs text-neutral-500">Every team mailbox appears separately in Email MasteBox.</p></div><button onClick={() => setAdding(adding ? null : 'choose')} className="inline-flex items-center gap-2 rounded-lg border border-brand-200 bg-white px-3 py-2 text-xs font-semibold text-brand-700 hover:bg-brand-50 dark:bg-neutral-900"><Plus className="h-4 w-4" />Add account</button></div>{accounts.length > 0 ? <div className="grid gap-3 lg:grid-cols-2">{accounts.map(account => <AccountCard key={account.id} account={account} />)}</div> : <div className="rounded-xl border border-dashed border-neutral-300 bg-white px-6 py-10 text-center dark:border-neutral-700 dark:bg-neutral-900"><Mail className="mx-auto mb-3 h-8 w-8 text-neutral-300" /><p className="font-semibold text-neutral-600">No email accounts connected</p><p className="mt-1 text-xs text-neutral-400">Choose a provider below to add your first mailbox.</p></div>}</section>
        <section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><div className="mb-5"><h2 className="text-lg font-semibold text-neutral-900 dark:text-white">Add another email account</h2><p className="text-sm text-neutral-500">There is no single-account restriction—repeat this process for every inbox your team manages.</p></div>{!adding || adding === 'choose' ? <div className="grid gap-4 md:grid-cols-3"><ProviderCard type="gmail" onClick={() => googleEnabled ? window.location.assign(route('client.inbox.email.google.connect')) : null} disabled={!googleEnabled} /><ProviderCard type="microsoft_365" onClick={() => microsoftEnabled ? window.location.assign(route('client.inbox.email.microsoft.connect')) : null} disabled={!microsoftEnabled} /><ProviderCard type="imap_smtp" onClick={() => setAdding('imap_smtp')} /></div> : <div className="mx-auto max-w-2xl rounded-xl border border-neutral-200 p-5 dark:border-neutral-700"><MailboxForm type={adding} imapExtensionAvailable={imapExtensionAvailable} onClose={() => setAdding('choose')} /></div>}
            {!googleEnabled && <p className="mt-4 text-xs text-amber-600">Google Mail OAuth must be configured by the Super Admin before Gmail accounts can connect.</p>}{!microsoftEnabled && <p className="mt-2 text-xs text-amber-600">Microsoft OAuth must be configured by the Super Admin before Microsoft accounts can connect.</p>}<details className="mt-5 rounded-lg bg-neutral-50 px-4 py-3 text-xs text-neutral-500 dark:bg-neutral-800"><summary className="cursor-pointer font-semibold">OAuth callback URLs</summary><div className="mt-2 space-y-2"><div><span className="font-medium">Google:</span><code className="ml-2 break-all">{googleCallbackUrl}</code></div><div><span className="font-medium">Microsoft:</span><code className="ml-2 break-all">{microsoftCallbackUrl}</code></div></div></details>
        </section>
    </div></ClientLayout>;
}

function ProviderCard({ type, onClick, disabled = false }) { const provider = providers[type]; return <button type="button" onClick={onClick} disabled={disabled} className="group rounded-xl border border-neutral-200 p-5 text-left transition hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-md disabled:cursor-not-allowed disabled:opacity-50 dark:border-neutral-700"><div className={`mb-4 flex h-11 w-11 items-center justify-center rounded-xl text-lg font-bold ${provider.color}`}>{provider.short}</div><h3 className="font-semibold text-neutral-900 dark:text-white">{provider.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-neutral-500">{provider.description}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-brand-600">Connect account<ChevronRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></button>; }
function Stat({ value, label, good, warning }) { return <div className="rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center gap-2"><span className={`text-2xl font-bold ${warning && value > 0 ? 'text-amber-600' : good ? 'text-emerald-600' : 'text-neutral-900 dark:text-white'}`}>{value}</span>{good && value > 0 && <CheckCircle2 className="h-4 w-4 text-emerald-500" />}</div><p className="text-xs text-neutral-500">{label}</p></div>; }
function Input({ label, value, onChange, type = 'text', optional = false }) { return <label className="block text-xs font-medium text-neutral-600 dark:text-neutral-300">{label}{optional && <span className="ml-1 font-normal text-neutral-400">(optional)</span>}<input required={!optional} type={type} value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-lg border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-800" /></label>; }
function Select({ label, value, onChange }) { return <label className="block text-xs font-medium text-neutral-600 dark:text-neutral-300">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-lg border-neutral-300 text-sm dark:border-neutral-700 dark:bg-neutral-800"><option value="ssl">SSL</option><option value="tls">STARTTLS</option><option value="none">None (not recommended)</option></select></label>; }
