<?php

// Code-reviewed product claims. Global copy and download destinations remain
// editable through Site Content; capability availability is resolved at runtime.
return [
    'pages' => [
        'products/omnichannel-inbox' => [
            'name' => 'Omni Inbox', 'icon' => 'inbox', 'demo' => 'inbox',
            'tagline' => 'Every conversation. A clear next step.',
            'description' => 'Bring customer messages into a shared workspace where your team can see the context, take ownership, and keep the conversation moving.',
            'benefits' => ['Connected customer channels', 'Clear agent ownership', 'Private notes and saved replies'],
            'sections' => [
                ['title' => 'The full conversation, right where you reply.', 'body' => 'Read the thread, view the contact, and respond without piecing together a customer story across different tabs.', 'points' => ['Website chat and supported messaging channels', 'Contact profiles, tags, and conversation history', 'Unread, open, and resolved conversation views']],
                ['title' => 'A team inbox needs a clear owner.', 'body' => 'Assign conversations, join a chat, and leave useful notes for the next teammate. Human ownership gives your team control when a conversation needs care.', 'points' => ['Assignment and joined-agent ownership', 'Human handoff from Smart Bots', 'Workspace-scoped notifications']],
                ['title' => 'Keep the reply moving on mobile.', 'body' => 'Your agents can continue supported conversation workflows in the dedicated mobile app, with the same workspace context.', 'points' => ['Android and iOS agent experience', 'Workspace-aware alerts', 'Shared conversation state']],
            ],
            'faq' => [['q' => 'Are emails in the same inbox?', 'a' => 'Email lives in Email MasterBox, a dedicated email workspace alongside Omni Inbox. Both are available in WisperBot.'], ['q' => 'Does every integration support direct messages?', 'a' => 'No. Messaging, publishing, comments, and commerce capabilities vary by provider. Check the integrations directory for the supported purpose.']],
            'related' => ['products/smart-ai-agent', 'products/email-masterbox', 'products/mobile-agent-app'],
        ],
        'products/smart-ai-agent' => [
            'name' => 'Smart AI Agent', 'icon' => 'sparkles', 'demo' => 'ai',
            'tagline' => 'Your knowledge. A more helpful first reply.',
            'description' => 'Give your Smart Bot the knowledge your customers need. Automate helpful answers, guide the next question, and bring a person in when it matters.',
            'benefits' => ['Knowledge Base answers', 'Suggested reply choices', 'AI schedules and human handoff'],
            'sections' => [
                ['title' => 'Start with what your business knows.', 'body' => 'Build a Knowledge Base from supported website sources and uploaded documents. Review and test answers before using them in customer conversations.', 'points' => ['Website and document sources', 'A guided review and testing workflow', 'Knowledge Base assignment per Smart Bot']],
                ['title' => 'Make the next step easier to choose.', 'body' => 'Useful follow-up questions can include compact reply choices. Customers select a choice or continue in their own words.', 'points' => ['Dynamic, industry-independent follow-ups', 'Website widget reply buttons', 'Compatible customer API payloads']],
                ['title' => 'Decide when AI takes the first turn.', 'body' => 'Choose an answering schedule and timezone, define fallback behavior, and let a teammate take over when a question needs a human.', 'points' => ['Always-on or scheduled answering', 'Configurable answer scope', 'Human control and conversation ownership']],
            ],
            'faq' => [['q' => 'Can a Smart Bot answer from our documents?', 'a' => 'Yes. Add supported documents or website sources to a Knowledge Base and assign it to your Smart Bot. Source quality and testing affect answer quality.'], ['q' => 'How do AI credits work?', 'a' => 'Managed AI actions use the credit rate shown in your workspace. The free plan includes 100 AI credits per month. You can review usage before upgrading.']],
            'related' => ['products/chatbots', 'products/automation', 'solutions/customer-support'],
        ],
        'products/chatbots' => [
            'name' => 'Website & WhatsApp Chatbots', 'icon' => 'messages', 'demo' => 'chat',
            'tagline' => 'A small chat window. A better customer experience.',
            'description' => 'Welcome website visitors with your own branded chat, connect them to a Smart Bot, and make a human conversation easy to reach.',
            'benefits' => ['White-label website chat', 'Compact reply choices', 'WhatsApp entry points'],
            'sections' => [
                ['title' => 'Make it feel like your business.', 'body' => 'Customize the widget appearance, welcome message, and Smart Bot. A compact conversation design keeps your website at the center.', 'points' => ['Brand colors and appearance controls', 'White-label chat experience', 'Responsive customer widget']],
                ['title' => 'Let the conversation find its way.', 'body' => 'Customers can type, choose a suggested reply, or ask for a person. Your team sees the conversation in Omni Inbox.', 'points' => ['AI follow-up choices', 'Human handoff', 'Attachments and supported audio input']],
                ['title' => 'Connect your website and app experience.', 'body' => 'Use the website embed for browsers and the customer chat SDK for your app. SDK features depend on the version released by your app team.', 'points' => ['Lightweight website embed', 'Signed customer identity support', 'Customer Chat SDK integration']],
            ],
            'faq' => [['q' => 'Is the website widget the same as a WhatsApp bot?', 'a' => 'Website chat creates a conversation inside your website. A WhatsApp entry point opens WhatsApp; automated WhatsApp replies require an eligible connected WhatsApp account.'], ['q' => 'Can I use my own branding?', 'a' => 'Yes. WisperBot supports a white-label website chatbot, including the free plan. Configure the appearance in your workspace.']],
            'related' => ['products/smart-ai-agent', 'developers', 'products/omnichannel-inbox'],
        ],
        'products/email-masterbox' => [
            'name' => 'Email MasterBox', 'icon' => 'mail', 'demo' => 'email',
            'tagline' => 'All your work mail. One focused workspace.',
            'description' => 'Connect Gmail, Microsoft, and supported IMAP mailboxes so your team can read and reply without switching accounts all day.',
            'benefits' => ['Multiple connected mailboxes', 'Threaded email replies', 'Shared team context'],
            'sections' => [
                ['title' => 'Give every mailbox a home.', 'body' => 'Connect supported email accounts and work through messages in a dedicated email workspace.', 'points' => ['Gmail and Microsoft connections', 'IMAP and SMTP support', 'Mailbox-aware conversation views']],
                ['title' => 'Keep email comfortable for your team.', 'body' => 'Read threads, compose replies, and work with attachments using a layout designed around email rather than a social-message feed.', 'points' => ['Threaded messages', 'Reply and compose workflows', 'Attachment support']],
                ['title' => 'Add AI on your own schedule.', 'body' => 'Configure the email answering policy separately from your other channels, with a selected Smart Bot and scheduled coverage.', 'points' => ['Separate email AI policy', 'Timezone-aware scheduling', 'Human ownership controls']],
            ],
            'faq' => [['q' => 'Does email share the social inbox?', 'a' => 'Email MasterBox is a separate email-focused interface inside the same WisperBot workspace.'], ['q' => 'Can AI answering be different for email?', 'a' => 'Yes. Email has its own answering policy, separate from Omni channels and website widget settings.']],
            'related' => ['products/omnichannel-inbox', 'products/smart-ai-agent', 'solutions/customer-support'],
        ],
        'products/automation' => [
            'name' => 'Visual Automations', 'icon' => 'workflow', 'demo' => 'automation',
            'tagline' => 'Build the follow-through into your workflow.',
            'description' => 'Turn repeatable customer tasks into visual flows. Connect triggers, conditions, and actions so your team can focus on the conversations that need them.',
            'benefits' => ['Visual workflow builder', 'Conditional routing', 'Connected actions'],
            'sections' => [
                ['title' => 'Draw the journey before you run it.', 'body' => 'Use a visual canvas to connect workflow steps and understand how a customer moves through your automation.', 'points' => ['Triggers and connected nodes', 'Conditions and branching', 'Workflow run visibility']],
                ['title' => 'Use context to choose the next step.', 'body' => 'Combine supported message events, contact information, and workflow conditions to route work consistently.', 'points' => ['Contact tags and segments', 'AI and message actions where supported', 'Delays and follow-up steps']],
                ['title' => 'Reach an audience with intention.', 'body' => 'Pair contact segments with supported WhatsApp templates and SMS campaigns. Provider rules, permissions, and sending costs still apply.', 'points' => ['Audience segmentation', 'WhatsApp template workflows', 'SMS campaign and gateway setup']],
            ],
            'faq' => [['q' => 'Do I need to write code?', 'a' => 'The visual builder supports no-code flows. Developers can extend supported workflows through APIs and webhooks.'], ['q' => 'Are campaign messages free?', 'a' => 'Provider messaging charges and plan limits can apply separately from WisperBot AI credits. Check the connected provider and your subscription.']],
            'related' => ['solutions/marketing-engagement', 'developers', 'products/smart-ai-agent'],
        ],
        'products/social-media' => [
            'name' => 'Social Media Automation', 'icon' => 'share', 'demo' => 'social',
            'tagline' => 'Plan the post. Keep the conversation going.',
            'description' => 'Organize supported social accounts, prepare content, and schedule publishing from a shared workspace.',
            'benefits' => ['Connected social accounts', 'Publishing calendar', 'Provider-aware controls'],
            'sections' => [
                ['title' => 'A clearer view of what goes out next.', 'body' => 'Bring supported social accounts into a publishing workflow with drafts, scheduling, and delivery status.', 'points' => ['Multi-account publishing', 'List and calendar views', 'Post delivery visibility']],
                ['title' => 'Respect what each platform supports.', 'body' => 'Content formats, post editing, and deletion differ by provider. WisperBot presents supported actions for each connected account.', 'points' => ['Platform-specific formats', 'Supported lifecycle actions', 'Reconnect guidance when access changes']],
                ['title' => 'Keep your content and support teams connected.', 'body' => 'Work on publishing alongside customer messaging and audience workflows, without assuming every social platform has the same inbox capabilities.', 'points' => ['Shared workspace access', 'Separate public and private conversations', 'Clear provider capability boundaries']],
            ],
            'faq' => [['q' => 'Can every platform receive direct messages here?', 'a' => 'No. Publishing access does not automatically provide direct-message or comment access. The integrations directory lists these separately.'], ['q' => 'Can I edit or delete every published post?', 'a' => 'Only where the provider and connected account support the action. Controls are capability-driven.']],
            'related' => ['channels/social-commerce', 'solutions/marketing-engagement', 'products/automation'],
        ],
        'products/mobile-agent-app' => [
            'name' => 'Mobile Agent App', 'icon' => 'phone', 'demo' => 'mobile',
            'tagline' => 'A helpful reply should not wait for a desk.',
            'description' => 'Give your team a dedicated Android and iOS agent experience for keeping up with customer conversations while away from their computer.',
            'benefits' => ['Android and iOS', 'Workspace-aware notifications', 'Customer conversation context'],
            'sections' => [
                ['title' => 'Your team inbox, within reach.', 'body' => 'Review supported conversations and reply from your phone with the customer context available to your workspace.', 'points' => ['Conversation list and message history', 'Agent reply workflows', 'Workspace-aware access']],
                ['title' => 'An alert that leads to the right place.', 'body' => 'Notifications carry workspace context so agents with multiple workspaces can open the relevant conversation.', 'points' => ['Workspace-specific notifications', 'Unread conversation awareness', 'Team availability support']],
                ['title' => 'One app for agents. An SDK for customers.', 'body' => 'The Agent App is for your team. The separate Customer Chat SDK adds a customer-facing conversation experience inside your own app.', 'points' => ['Dedicated staff experience', 'Separate customer SDK', 'Version-specific mobile feature availability']],
            ],
            'faq' => [['q' => 'Is the Agent App the customer chat SDK?', 'a' => 'No. Agents use the WisperBot app to handle conversations. Your developers use the Customer Chat SDK to add chat to your own customer app.'], ['q' => 'Where can I download it?', 'a' => 'Available official store links appear in the Download menu. Contact us if your organization needs help with access.']],
            'related' => ['products/omnichannel-inbox', 'developers', 'solutions/customer-support'],
        ],
        'solutions/customer-support' => [
            'name' => 'Customer Support', 'icon' => 'headphones', 'demo' => 'inbox',
            'tagline' => 'Give every customer a way forward.',
            'description' => 'Connect the inbox, your business knowledge, and the people who can help. Let AI handle a useful first answer while your team owns the relationship.',
            'benefits' => ['Fewer disconnected inboxes', 'Knowledge-led first answers', 'Clear human handoff'],
            'sections' => [
                ['title' => 'Meet customers where they ask.', 'body' => 'Bring supported website and messaging conversations into Omni Inbox, and work on email in Email MasterBox.', 'points' => ['Connected channel context', 'Dedicated email workspace', 'One contact history where available']],
                ['title' => 'Make repeat questions easier to handle.', 'body' => 'Use your approved knowledge to guide a Smart Bot, then test the questions your customers actually ask.', 'points' => ['Knowledge Base training', 'Suggested follow-up choices', 'Fallback and human help']],
                ['title' => 'Let your people do the human part.', 'body' => 'Assign ownership, add notes, and continue on mobile when a conversation needs a personal response.', 'points' => ['Agent ownership', 'Team notifications', 'Mobile follow-through']],
            ],
            'faq' => [['q' => 'Can we keep human support?', 'a' => 'Yes. AI and human support work together, with handoff and joined-agent ownership.'], ['q' => 'Can we start with one channel?', 'a' => 'Yes. The free plan includes one channel and 100 monthly AI credits.']],
            'related' => ['products/omnichannel-inbox', 'products/smart-ai-agent', 'products/mobile-agent-app'],
        ],
        'solutions/sales-lead-generation' => [
            'name' => 'Sales & Lead Generation', 'icon' => 'target', 'demo' => 'chat',
            'tagline' => 'Turn a first question into a real conversation.',
            'description' => 'Help visitors explore your offer, collect useful contact context, and connect interested customers with your team.',
            'benefits' => ['Website conversations', 'Helpful guided choices', 'Contact organization'],
            'sections' => [
                ['title' => 'Be there at the moment of interest.', 'body' => 'A branded widget gives a visitor an easy way to ask about your business while they are already on your website.', 'points' => ['Website chatbot', 'Business knowledge answers', 'WhatsApp contact entry point']],
                ['title' => 'Help people tell you what they need.', 'body' => 'Use grounded follow-up questions and meaningful reply choices to make the next turn easier.', 'points' => ['Dynamic conversation choices', 'Contact profiles and fields', 'Tags and audience segments']],
                ['title' => 'Give the right teammate the context.', 'body' => 'Continue the conversation with the history available, instead of asking the customer to explain everything again.', 'points' => ['Assignment and handoff', 'Shared message history', 'Supported follow-up automations']],
            ],
            'faq' => [['q' => 'Does the bot make sales promises?', 'a' => 'Configure it around your business knowledge and answer scope. Prices, policies, and availability should come from verified business information.'], ['q' => 'Can visitors ask for a person?', 'a' => 'Yes. The website chat supports human handoff.']],
            'related' => ['products/chatbots', 'products/automation', 'products/omnichannel-inbox'],
        ],
        'solutions/ecommerce-marketplaces' => [
            'name' => 'Ecommerce & Marketplaces', 'icon' => 'store', 'demo' => 'commerce',
            'tagline' => 'Better shopping conversations start with context.',
            'description' => 'Connect supported stores and seller accounts so your team can work with useful product and order context alongside customer support.',
            'benefits' => ['Store connections', 'Product and order context', 'Supported seller workflows'],
            'sections' => [
                ['title' => 'Bring store context into your workspace.', 'body' => 'Connect supported Shopify, WooCommerce, and BigCommerce stores to work with synced commerce records.', 'points' => ['Connected store accounts', 'Product records', 'Order visibility']],
                ['title' => 'Help customers understand their options.', 'body' => 'Use a Knowledge Base for your buying guides, product explanations, and published policies. Keep personalized account questions with authorized workflows or your team.', 'points' => ['Knowledge-led buying guidance', 'Website chat and messaging', 'Human help for account-specific needs']],
                ['title' => 'Treat each marketplace on its own terms.', 'body' => 'eBay seller messaging and Amazon buyer communication have different provider rules. WisperBot keeps those supported workflows distinct.', 'points' => ['eBay seller messages', 'Amazon order-specific buyer communication', 'Provider approval and account eligibility']],
            ],
            'faq' => [['q' => 'Is Amazon a general live-chat channel?', 'a' => 'No. Amazon communication is limited to supported order-specific buyer messaging and provider policies.'], ['q' => 'Does connecting a store automatically authorize transactions?', 'a' => 'No. Store connections provide supported commerce workflows. Public AI guidance is not a substitute for authenticated order actions.']],
            'related' => ['channels/social-commerce', 'products/chatbots', 'products/smart-ai-agent'],
        ],
        'solutions/marketing-engagement' => [
            'name' => 'Marketing & Engagement', 'icon' => 'megaphone', 'demo' => 'social',
            'tagline' => 'Keep your next conversation connected.',
            'description' => 'Organize contacts, plan social content, and run supported messaging campaigns from the same platform your team uses to respond.',
            'benefits' => ['Audience segments', 'Social publishing', 'WhatsApp and SMS campaigns'],
            'sections' => [
                ['title' => 'Start with a useful audience.', 'body' => 'Use contact fields, tags, and segments to organize who you need to reach.', 'points' => ['Contact profiles', 'Tags and segments', 'Import and organization tools']],
                ['title' => 'Plan a consistent publishing rhythm.', 'body' => 'Prepare and schedule supported posts across your connected social accounts, with visibility into delivery.', 'points' => ['Shared content planning', 'Publishing calendar', 'Platform-specific actions']],
                ['title' => 'Follow up through supported channels.', 'body' => 'Use WhatsApp templates, SMS campaigns, and visual workflows where supported. Respect consent and provider messaging policies.', 'points' => ['Approved WhatsApp templates', 'Configured SMS gateways', 'Campaign status and automation runs']],
            ],
            'faq' => [['q' => 'Does one permission unlock every social action?', 'a' => 'No. Publishing, direct messages, and comments use different capabilities and provider permissions.'], ['q' => 'Are provider costs included?', 'a' => 'Provider charges may apply separately. Check your plan, messaging provider, and AI-credit allowance.']],
            'related' => ['products/social-media', 'products/automation', 'channels/social-commerce'],
        ],
        'channels/customer-messaging' => [
            'name' => 'Customer Messaging Channels', 'icon' => 'globe', 'demo' => 'inbox',
            'tagline' => 'Be easy to reach. Stay easy to manage.',
            'description' => 'Connect website chat, WhatsApp, Messenger, Instagram Direct, and Telegram Business. Bring supported email accounts into Email MasterBox.',
            'benefits' => ['Official provider connections', 'Shared team workflows', 'Channel-specific controls'],
            'sections' => [
                ['title' => 'Meet the message in the right workspace.', 'body' => 'Customer messaging belongs in Omni Inbox. Email belongs in Email MasterBox. Both give your team a focused place to reply.', 'points' => ['Website and app chat', 'Supported Meta and Telegram messaging', 'Gmail, Microsoft, and IMAP mailboxes']],
                ['title' => 'Keep channel rules visible.', 'body' => 'Connection access, reply windows, templates, and attachment support vary by provider. Configure accounts through their supported authorization flows.', 'points' => ['Customer-authorized accounts', 'WhatsApp template rules', 'Connection and reconnect guidance']],
                ['title' => 'Choose how much to automate.', 'body' => 'Use Smart Bot policies and visual workflows where supported, with a human team available for the conversation that needs one.', 'points' => ['Channel AI answering policies', 'Scheduled coverage', 'Human ownership']],
            ],
            'faq' => [['q' => 'Can I connect an ordinary personal account?', 'a' => 'Eligibility varies. Some providers require business accounts, professional profiles, approved assets, or specific permissions.'], ['q' => 'Does SMS behave like a live chat inbox?', 'a' => 'SMS is offered through supported campaign and gateway workflows. Do not assume identical capabilities to website chat.']],
            'related' => ['products/omnichannel-inbox', 'products/email-masterbox', 'products/automation'],
        ],
        'channels/social-commerce' => [
            'name' => 'Social & Commerce Connections', 'icon' => 'network', 'demo' => 'commerce',
            'tagline' => 'Connect more of the customer journey.',
            'description' => 'Bring social publishing, commerce context, and supported seller communication into your workspace, with clear capabilities for every provider.',
            'benefits' => ['Social publishing accounts', 'Store integrations', 'Seller communication'],
            'sections' => [
                ['title' => 'Publish where your audience follows.', 'body' => 'Work with supported Facebook, Instagram, LinkedIn, X, TikTok, and YouTube publishing connections. Formats and account eligibility differ.', 'points' => ['Supported media publishing', 'Scheduling and status', 'Provider-specific edit and delete actions']],
                ['title' => 'Connect the store behind the question.', 'body' => 'Use Shopify, WooCommerce, and BigCommerce connections for supported products and order workflows.', 'points' => ['Store account connections', 'Product context', 'Order records']],
                ['title' => 'Give seller conversations the right boundaries.', 'body' => 'Amazon and eBay use their own authorization, policy, and message rules. Access depends on the connected seller account.', 'points' => ['eBay seller messaging', 'Amazon order communication', 'Capability-aware operations']],
            ],
            'faq' => [['q' => 'Can I reply to comments on every connected platform?', 'a' => 'No. Comment support is separately permissioned and released by provider. A publishing connection does not imply comment access.'], ['q' => 'Where do I compare capabilities?', 'a' => 'The integrations directory labels messaging, email, publishing, commerce, and developer capabilities separately.']],
            'related' => ['products/social-media', 'solutions/ecommerce-marketplaces', 'solutions/marketing-engagement'],
        ],
        'developers' => [
            'name' => 'Developer Platform', 'icon' => 'code', 'demo' => 'developer',
            'tagline' => 'Your product. Connected to every conversation.',
            'description' => 'Embed customer chat, connect your systems with REST APIs, and respond to events through webhooks. Build on your workspace with explicit access boundaries.',
            'benefits' => ['Customer Chat SDK', 'REST API', 'Event webhooks'],
            'sections' => [
                ['title' => 'Put customer chat inside your app.', 'body' => 'The Flutter customer chat SDK gives your app team a dedicated integration path. Use the published package documentation for supported versions and features.', 'points' => ['Flutter package integration', 'Customer identity support', 'Separate SDK release lifecycle']],
                ['title' => 'Connect the systems your team uses.', 'body' => 'Use authenticated APIs for supported workspace resources. Developer tools availability depends on your account entitlement.', 'points' => ['Workspace-scoped access', 'Sanctum bearer authentication', 'Structured API responses']],
                ['title' => 'Let events carry the next step.', 'body' => 'Connect supported outbound events to your systems through webhooks, and build integrations around explicit event contracts.', 'points' => ['Event-driven integrations', 'API tokens and access controls', 'Documentation and integration guidance']],
            ],
            'faq' => [['q' => 'Is the SDK the Agent App?', 'a' => 'No. The SDK embeds customer chat inside your app. The WisperBot Agent App is used by your staff to reply.'], ['q' => 'Where are the SDK and API documentation?', 'a' => 'Configured public documentation and pub.dev links appear here and in the Download menu. Contact us for access if your account requires a developer-tools entitlement.']],
            'related' => ['products/chatbots', 'products/automation', 'products/mobile-agent-app'],
        ],
    ],
    'integrations' => [
        ['name' => 'Website Chat', 'key' => 'website', 'category' => 'messaging', 'capabilities' => ['Inbox', 'AI', 'Widget'], 'note' => 'Branded chat on your website.'],
        ['name' => 'WhatsApp', 'key' => 'whatsapp', 'category' => 'messaging', 'capabilities' => ['Inbox', 'AI', 'Templates'], 'note' => 'Business account eligibility and Meta messaging rules apply.'],
        ['name' => 'Facebook', 'key' => 'facebook', 'category' => 'social', 'capabilities' => ['Inbox', 'Publishing'], 'note' => 'Messenger and Page publishing use separate permissions.'],
        ['name' => 'Instagram', 'key' => 'instagram', 'category' => 'social', 'capabilities' => ['Inbox', 'Publishing'], 'note' => 'Eligible professional accounts and approved permissions required.'],
        ['name' => 'Telegram Business', 'key' => 'telegram', 'category' => 'messaging', 'capabilities' => ['Inbox', 'AI'], 'note' => 'Connected Telegram Business account required.'],
        ['name' => 'Gmail', 'key' => 'gmail', 'category' => 'email', 'capabilities' => ['Email'], 'note' => 'Read and reply in Email MasterBox.'],
        ['name' => 'Microsoft Mail', 'key' => 'microsoft', 'category' => 'email', 'capabilities' => ['Email'], 'note' => 'Connected Microsoft mailboxes in Email MasterBox.'],
        ['name' => 'IMAP / SMTP', 'key' => 'email', 'category' => 'email', 'capabilities' => ['Email'], 'note' => 'Supported mail servers and credentials required.'],
        ['name' => 'LinkedIn', 'key' => 'linkedin', 'category' => 'social', 'capabilities' => ['Publishing'], 'note' => 'Account and organization permissions determine publishing access.'],
        ['name' => 'X', 'key' => 'x', 'category' => 'social', 'capabilities' => ['Publishing'], 'note' => 'X API plan, credits, and account access may be required.'],
        ['name' => 'TikTok', 'key' => 'tiktok', 'category' => 'social', 'capabilities' => ['Publishing'], 'note' => 'Provider-approved publishing scope and media rules apply.'],
        ['name' => 'YouTube', 'key' => 'youtube', 'category' => 'social', 'capabilities' => ['Publishing'], 'note' => 'Supported video publishing; provider account and quota rules apply.'],
        ['name' => 'Shopify', 'key' => 'shopify', 'category' => 'commerce', 'capabilities' => ['Commerce'], 'note' => 'Supported store, product, and order workflows.'],
        ['name' => 'WooCommerce', 'key' => 'woocommerce', 'category' => 'commerce', 'capabilities' => ['Commerce'], 'note' => 'Supported store, product, and order workflows.'],
        ['name' => 'BigCommerce', 'key' => 'bigcommerce', 'category' => 'commerce', 'capabilities' => ['Commerce'], 'note' => 'Supported store, product, and order workflows.'],
        ['name' => 'eBay', 'key' => 'ebay', 'category' => 'commerce', 'capabilities' => ['Seller messaging'], 'note' => 'Authorized seller accounts and supported message operations.'],
        ['name' => 'Amazon', 'key' => 'amazon', 'category' => 'commerce', 'capabilities' => ['Order communication'], 'note' => 'Order-specific buyer messages; not a general chat inbox.'],
        ['name' => 'SMS Gateways', 'key' => 'sms', 'category' => 'messaging', 'capabilities' => ['Campaigns'], 'note' => 'Configured providers, sending charges, and consent rules apply.'],
        ['name' => 'REST API & Webhooks', 'key' => 'api', 'category' => 'developer', 'capabilities' => ['Developer'], 'note' => 'Workspace-scoped integrations; entitlement may be required.'],
        ['name' => 'Customer Chat SDK', 'key' => 'sdk', 'category' => 'developer', 'capabilities' => ['SDK'], 'note' => 'Flutter customer chat; feature availability depends on package version.'],
    ],
];
